recognize bunched footnote references and fix those visually by pulling them apart by injecting a simple comma in the superscript sequence.
Test has been augmented accordingly.

From the code comments:

 check if multiple footnote references are bunched together:
 IFF they are, we should separate them with commas.

 Exception: when next token has an extra text (`meta.text`) the
 bunching together is not a problem as them the output will render
 like this: `bla<sup>1</sup><a>text<sup>2</sup></a>`, ergo a look
 like this: `bla¹text²` instead of bunched footnotes references ¹ and ²
 that would (without the extra comma injection) look like `bla¹²` instead
 of `x¹⁺²` (here '+' instead of ',' comma, but you get the idea -- there's no
 Unicode superscript-comma so that's why I used unicode superscript-plus
 in this 'ascii art' example).